INSERT INTO MenuItems (Id, Name, Description, Price, Category)
VALUES
    (NEWID(), 'Margherita Pizza', 'Classic cheese and tomato pizza.', 9.99, 'Pizza'),
    (NEWID(), 'Pepperoni Pizza', 'Pizza topped with pepperoni slices.', 12.99, 'Pizza'),
    (NEWID(), 'BBQ Chicken Wings', 'Grilled chicken wings with BBQ sauce.', 6.99, 'Appetizers'),
    (NEWID(), 'Garlic Bread', 'Toasted bread with garlic and butter.', 4.99, 'Appetizers'),
    (NEWID(), 'Caesar Salad', 'Fresh lettuce with Caesar dressing.', 7.49, 'Salads'),
    (NEWID(), 'Greek Salad', 'Salad with feta cheese, olives, and cucumbers.', 8.99, 'Salads'),
    (NEWID(), 'Cheeseburger', 'Beef burger with cheese, lettuce, and tomato.', 10.49, 'Burgers'),
    (NEWID(), 'Veggie Burger', 'Plant-based burger with fresh veggies.', 9.49, 'Burgers'),
    (NEWID(), 'Spaghetti Bolognese', 'Pasta with meat sauce.', 11.99, 'Pasta'),
    (NEWID(), 'Fettuccine Alfredo', 'Pasta in creamy Alfredo sauce.', 12.99, 'Pasta'),
    (NEWID(), 'Chocolate Cake', 'Rich and moist chocolate cake.', 5.99, 'Desserts'),
    (NEWID(), 'Tiramisu', 'Classic Italian coffee-flavored dessert.', 6.99, 'Desserts'),
    (NEWID(), 'Cappuccino', 'Hot espresso coffee with steamed milk foam.', 3.99, 'Beverages'),
    (NEWID(), 'Iced Tea', 'Cold and refreshing tea.', 2.99, 'Beverages'),
    (NEWID(), 'Penne Arrabiata', 'Pasta with spicy tomato sauce.', 10.99, 'Pasta'),
    (NEWID(), 'Chicken Alfredo Pizza', 'Pizza with creamy Alfredo sauce and chicken.', 13.99, 'Pizza'),
    (NEWID(), 'Buffalo Wings', 'Spicy chicken wings with Buffalo sauce.', 7.49, 'Appetizers'),
    (NEWID(), 'Mozzarella Sticks', 'Fried mozzarella cheese sticks.', 5.99, 'Appetizers'),
    (NEWID(), 'House Salad', 'Mixed greens with house dressing.', 6.99, 'Salads'),
    (NEWID(), 'Chicken Caesar Salad', 'Caesar salad topped with grilled chicken.', 9.99, 'Salads'),
    (NEWID(), 'Double Cheeseburger', 'Double patty burger with cheese and toppings.', 12.49, 'Burgers'),
    (NEWID(), 'Grilled Chicken Sandwich', 'Grilled chicken breast sandwich.', 9.99, 'Burgers'),
    (NEWID(), 'Lasagna', 'Layered pasta with meat, cheese, and tomato sauce.', 13.49, 'Pasta'),
    (NEWID(), 'Pesto Pasta', 'Pasta tossed in fresh basil pesto.', 11.99, 'Pasta'),
    (NEWID(), 'Apple Pie', 'Traditional apple pie with cinnamon.', 5.49, 'Desserts'),
    (NEWID(), 'Ice Cream Sundae', 'Vanilla ice cream with toppings.', 4.99, 'Desserts'),
    (NEWID(), 'Latte', 'Smooth espresso with steamed milk.', 4.49, 'Beverages'),
    (NEWID(), 'Orange Juice', 'Freshly squeezed orange juice.', 3.99, 'Beverages'),
    (NEWID(), 'Hawaiian Pizza', 'Pizza with ham and pineapple.', 11.99, 'Pizza'),
    (NEWID(), 'Veggie Pizza', 'Pizza topped with assorted vegetables.', 10.99, 'Pizza'),
    (NEWID(), 'Stuffed Mushrooms', 'Mushrooms stuffed with cheese and herbs.', 6.99, 'Appetizers'),
    (NEWID(), 'French Fries', 'Crispy golden fries.', 3.99, 'Appetizers'),
    (NEWID(), 'Asian Chicken Salad', 'Salad with Asian-style grilled chicken.', 9.49, 'Salads'),
    (NEWID(), 'Avocado Salad', 'Salad with fresh avocado slices.', 8.99, 'Salads'),
    (NEWID(), 'Bacon Cheeseburger', 'Burger topped with bacon and cheese.', 11.49, 'Burgers'),
    (NEWID(), 'Mushroom Swiss Burger', 'Burger with mushrooms and Swiss cheese.', 10.99, 'Burgers'),
    (NEWID(), 'Ravioli', 'Pasta stuffed with cheese or meat.', 12.49, 'Pasta'),
    (NEWID(), 'Seafood Pasta', 'Pasta with shrimp and scallops.', 14.99, 'Pasta'),
    (NEWID(), 'Brownie', 'Chocolate brownie served warm.', 4.99, 'Desserts'),
    (NEWID(), 'Cheesecake', 'Classic New York-style cheesecake.', 6.49, 'Desserts'),
    (NEWID(), 'Espresso', 'Strong and rich coffee shot.', 2.99, 'Beverages'),
    (NEWID(), 'Smoothie', 'Fresh fruit blended drink.', 4.99, 'Beverages'),
    (NEWID(), 'Meat Lovers Pizza', 'Pizza with sausage, pepperoni, and bacon.', 14.99, 'Pizza'),
    (NEWID(), 'BBQ Beef Pizza', 'Pizza with BBQ sauce and beef.', 12.99, 'Pizza'),
    (NEWID(), 'Onion Rings', 'Crispy fried onion rings.', 4.99, 'Appetizers'),
    (NEWID(), 'Spinach Artichoke Dip', 'Warm spinach and artichoke dip.', 7.99, 'Appetizers'),
    (NEWID(), 'Cobb Salad', 'Salad with bacon, egg, and chicken.', 10.99, 'Salads'),
    (NEWID(), 'Caprese Salad', 'Salad with mozzarella, tomato, and basil.', 8.49, 'Salads'),
    (NEWID(), 'Turkey Burger', 'Grilled turkey patty with toppings.', 9.99, 'Burgers'),
    (NEWID(), 'BBQ Pulled Pork Sandwich', 'Pulled pork with BBQ sauce.', 10.99, 'Burgers'),
    (NEWID(), 'Mac and Cheese', 'Creamy macaroni and cheese.', 8.99, 'Pasta'),
    (NEWID(), 'Lobster Ravioli', 'Ravioli stuffed with lobster.', 15.99, 'Pasta'),
    (NEWID(), 'Panna Cotta', 'Creamy Italian dessert.', 6.49, 'Desserts'),
    (NEWID(), 'Creme Brulee', 'Rich custard with caramelized sugar.', 7.49, 'Desserts'),
    (NEWID(), 'Americano', 'Espresso with hot water.', 2.99, 'Beverages'),
    (NEWID(), 'Hot Chocolate', 'Warm and creamy chocolate drink.', 3.49, 'Beverages');

INSERT INTO DeliveryStaff (Id, FirstName, LastName, Phone, Email)
VALUES
    (NEWID(), 'John', 'Doe', '+30 210 123 4567', 'john.doe@example.com'),
    (NEWID(), 'Jane', 'Smith', '+30 210 234 5678', 'jane.smith@example.com'),
    (NEWID(), 'Michael', 'Johnson', '+30 231 456 7890', 'michael.johnson@example.com'),
    (NEWID(), 'Emily', 'Davis', '+30 231 567 8901', 'emily.davis@example.com'),
    (NEWID(), 'Chris', 'Brown', '+30 210 678 9012', 'chris.brown@example.com'),
    (NEWID(), 'Sarah', 'Taylor', '+30 210 789 0123', 'sarah.taylor@example.com'),
    (NEWID(), 'James', 'Wilson', '+30 231 890 1234', 'james.wilson@example.com'),
    (NEWID(), 'Anna', 'Moore', '+30 231 901 2345', 'anna.moore@example.com'),
    (NEWID(), 'Robert', 'Anderson', '+30 210 012 3456', 'robert.anderson@example.com'),
    (NEWID(), 'Olivia', 'Thomas', '+30 210 123 4568', 'olivia.thomas@example.com');

	INSERT INTO Customers (Id, FirstName, LastName, Phone, Email)
VALUES 
    (NEWID(), 'Nikos', 'Papadopoulos', '6941234567', 'nikos.papadopoulos@example.com'),
    (NEWID(), 'Maria', 'Karatza', '6939876543', 'maria.karatza@example.com'),
    (NEWID(), 'Kostas', 'Vlachos', '6951122334', 'kostas.vlachos@example.com'),
    (NEWID(), 'Eleni', 'Giannakou', '6976543210', 'eleni.giannakou@example.com'),
    (NEWID(), 'Giorgos', 'Stefanidis', '6998765432', 'giorgos.stefanidis@example.com');